version: '3.8'

services:
  # MySQL Database
  mysql:
    image: mysql:8.0
    container_name: qqe_mysql
    environment:
      MYSQL_ROOT_PASSWORD: QqeRoot2025!
      MYSQL_DATABASE: grader_marketplace
      MYSQL_USER: qqe_user
      MYSQL_PASSWORD: QqeApp2025!
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/simple_schema.sql:/docker-entrypoint-initdb.d/schema.sql
    networks:
      - qqe_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  # Backend API
  backend:
    build: ./server
    container_name: qqe_backend
    environment:
      DB_HOST: mysql
      DB_USER: qqe_user
      DB_PASSWORD: QqeApp2025!
      DB_NAME: grader_marketplace
      DB_PORT: 3306
      JWT_SECRET: QqeJWTSecret2025!
      SESSION_SECRET: QqeSessionSecret2025!
      COOKIE_SECRET: QqeCookieSecret2025!
      NODE_ENV: production
      PORT: 3000
      FRONTEND_URL: http://localhost:80
    ports:
      - "3001:3000"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - qqe_network
    volumes:
      - ./server/uploads:/app/uploads
    restart: unless-stopped

  # Frontend (Production Build)
  frontend:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: qqe_frontend
    environment:
      VITE_API_URL: http://localhost:3000/api
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - qqe_network
    restart: unless-stopped

volumes:
  mysql_data:

networks:
  qqe_network:
    driver: bridge
